# -*- coding: utf-8 -*-
"""Area de un cirvulo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUU1Wu6p1TgWFLH02F0wgQKHISreg8TT
"""

#AREA DE UN CIRCULO
# Función para calcular el área del círculo
def area_circulo(radio): # pi * r**2
    return 3.14 * radio * radio
def volumen_cilindro(radio, altura): #V=pi r**2 *h
    return area_circulo(radio) * altura
r = float(input("Ingresa el radio: "))
h = float(input("Ingresa la altura: "))
print("Área del círculo:", area_circulo(r))
print("Volumen del cilindro:", volumen_cilindro(r, h))