# -*- coding: utf-8 -*-
"""Contraseña

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXm6KTiMNsBnQS1_ucih3O85au4YbE18
"""

contraseña = "FGOLDENBOY"
while True:
  usuario = input("Ingresar contraseña: ")
  if usuario == contraseña:
    print("Contraseña correcta")
    break
  else:
      print("Contraseña incorrecta, intenta de nuevo")