# -*- coding: utf-8 -*-
"""COPIA LA PALABRA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of9c_COftfFTkbWSeTgH2Aend2cdHsph
"""

palabra = input("Escribe una palabra: ")

for i in range(15):
    print(palabra)