# -*- coding: utf-8 -*-
"""csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOHfLZ7BeUC3VeucjGFd2X1AnF-BsG6n
"""

import csv

with open("ventas.csv" , "r") as archivo:
  lector = csv.reader(archivo)
  for fila in lector:
    print(fila)

#TOTAL DEL PRODUCTOS
import csv
total = 0
with open("ventas.csv" , "r") as archivo:
  lector = csv.DictReader(archivo)

  for fila in lector:
    #print(fila)
    cantidad = int(fila["Cantidad"])
    precio = float(fila["Precio_Unitario"])
    total += cantidad * precio
print("Ventas totales:", total)

#

import csv
archivo_csv = "calificaciones.csv"
suma_promedios_grupo = 0
total_alumnos = 0
aprobados = 0
reprobados = 0
mejor_alumno = ""
peor_alumno = ""
mejor_promedio = -1
peor_promedio = 101
lista_alumnos = []
try:
    with open(archivo_csv, "r", encoding="utf-8") as archivo:
        lector = csv.reader(archivo)
        next(lector)

        for fila in lector:
            nombre = fila[1]
            p1, p2, p3 = int(fila[3]), int(fila[4]), int(fila[5])

            promedio_alumno = (p1 + p2 + p3) / 3

            suma_promedios_grupo += promedio_alumno
            total_alumnos += 1

            if promedio_alumno >= 70:
                aprobados += 1
            else:
                reprobados += 1

            if promedio_alumno > mejor_promedio:
                mejor_promedio = promedio_alumno
                mejor_alumno = nombre

            if promedio_alumno < peor_promedio:
                peor_promedio = promedio_alumno
                peor_alumno = nombre

            lista_alumnos.append((nombre, promedio_alumno))

    if total_alumnos > 0:
        promedio_general = suma_promedios_grupo / total_alumnos
        print(f" {total_alumnos}  el promedio general del grupo quedó en {promedio_general:.2f}.")
        print(f" {aprobados} alumnos lograron aprobar la materia, mientras que {reprobados} fueron reprobados.")
        print(f" el promedio más alto lo obtuvo {mejor_alumno} con un total de {mejor_promedio:.2f}, que el más bajo fue el de {peor_alumno} con {peor_promedio:.2f}.\n")
        lista_alumnos.sort(key=lambda x: x[1], reverse=True)

        print("Lista ordenada de alumnos de mayor a menor promedio:")
        for puesto, (nombre, promedio) in enumerate(lista_alumnos, start=1):
            print(f"Posición {puesto}: {nombre} con un promedio de {promedio:.2f}")

    else:
        print("No se encontraron registros de alumnos para procesar en el archivo.")

except FileNotFoundError:
    print(f"No pude encontrar el archivo '{archivo_csv}'. Revisa que esté en la misma carpeta.")

import csv

data_ventas = [
    ['ID_Venta', 'Fecha', 'Producto', 'Categoria', 'Cantidad', 'Precio_Unitario', 'Ciudad', 'Vendedor'],
    ['1', '2026-01-05', 'Laptop HP', 'Laptops', '2', '14500', 'CDMX', 'Ana'],
    ['2', '2026-01-05', 'Mouse Logitech', 'Accesorios', '5', '350', 'CDMX', 'Carlos'],
    ['3', '2026-01-06', 'Monitor Samsung', 'Monitores', '1', '4200', 'Puebla', 'Ana'],
    ['4', '2026-01-06', 'Teclado Redragon', 'Accesorios', '3', '850', 'Toluca', 'Luis'],
    ['5', '2026-01-07', 'Laptop Lenovo', 'Laptops', '1', '16500', 'Puebla', 'Carlos'],
    ['6', '2026-01-08', 'SSD Kingston', 'Almacenamiento', '4', '1200', 'CDMX', 'Ana'],
    ['7', '2026-01-08', 'Memoria RAM 16GB', 'Componentes', '3', '1800', 'Toluca', 'Luis'],
    ['8', '2026-01-09', 'Monitor LG', 'Monitores', '2', '3900', 'Puebla', 'Carlos'],
    ['9', '2026-01-10', 'Laptop ASUS', 'Laptops', '1', '17500', 'CDMX', 'Ana'],
    ['10', '2026-01-10', 'Mouse Logitech', 'Accesorios', '6', '350', 'Toluca', 'Luis'],
    ['11', '2026-01-11', 'SSD Kingston', 'Almacenamiento', '2', '1200', 'Puebla', 'Carlos'],
    ['12', '2026-01-12', 'Teclado Redragon', 'Accesorios', '2', '850', 'CDMX', 'Ana'],
    ['13', '2026-01-12', 'Monitor Samsung', 'Monitores', '1', '4200', 'Toluca', 'Luis'],
    ['14', '2026-01-13', 'Laptop HP', 'Laptops', '1', '14500', 'Puebla', 'Carlos'],
    ['15', '2026-01-14', 'Memoria RAM 16GB', 'Componentes', '5', '1800', 'CDMX', 'Ana'],
    ['16', '2026-01-15', 'SSD Kingston', 'Almacenamiento', '3', '1200', 'Toluca', 'Luis'],
    ['17', '2026-01-15', 'Monitor LG', 'Monitores', '1', '3900', 'CDMX', 'Ana'],
    ['18', '2026-01-16', 'Laptop Lenovo', 'Laptops', '2', '16500', 'Puebla', 'Carlos'],
    ['19', '2026-01-17', 'Mouse Logitech', 'Accesorios', '8', '350', 'Toluca', 'Luis'],
    ['20', '2026-01-18', 'Memoria RAM 16GB', 'Componentes', '2', '1800', 'CDMX', 'Ana']
]

with open('ventas.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data_ventas)

print("ventas.csv created successfully.")

