# -*- coding: utf-8 -*-
"""Factura iva

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cODAuzhrZ8ixcPZbp0s7u0MAHjLm64yc
"""

#FACTURAS IVA
def total_factura(cantidad, iva=21):
    total = cantidad + (cantidad * iva / 100)
    return total
cantidad = float(input("Ingresa la cantidad sin IVA: "))
print("Total con IVA:", total_factura(cantidad))