# -*- coding: utf-8 -*-
"""FIZZ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14udIO4DQDjuroI7T4bpmgEJphYu-5CkG
"""

for numero in range(1, 101):

    if numero % 3 == 0 and numero % 5 == 0:
        print("fizzbuzz")

    elif numero % 3 == 0:
        print("fizz")

    elif numero % 5 == 0:
        print("buzz")

    else:
        print(numero)