# -*- coding: utf-8 -*-
"""LISTA DE ESTUDIANTES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UySGj9vvIpqL8MwffS-yE2v8NED-YuR
"""

#Creacion lista
alumnos = ["Fernando","Isaac"]
estudiantes =[]
estudiantes = alumnos.copy()
print(alumnos, "alumnos")
print(estudiantes,"estudiantes")
estudiantes.pop() #elimina el ultimo elemento
print(estudiantes,"estudiantes")
print(alumnos,"alumnos")
estudiantes.append("RODRIGO")
print(estudiantes, "estudiantes")
print(alumnos.count("Jose"))
print(len(alumnos))