# -*- coding: utf-8 -*-
"""Operacion Aritmetica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DHhDQxZ-VREDJ01Q7bRP4dKBe-YNfe3
"""

#EJERCICIO 1
hermanos = 3; #int Fernando
print("Yo tengo",hermanos,"hermanos.")

estatura = 1.83 #float
print("Mi estatura es de",estatura,"m.")

esMayor = True #boolean
print("¿La persona es mayor de edad?",esMayor)

domicilio = "Av. Ing. Militares y Av. Mexico Tacuba" #string
print("La UTC Toreo se encuentra en",domicilio)


#EJERCICIO 2
resultado = ((3 + 7) / (2 * 6)) ** 2

print("El resultado es:", resultado)

#EJERCICIO 3
dividendo = int(input("Ingresa el dividendo: "))
divisor = int(input("Ingresa el divisor:"))
cociente = dividendo // divisor
residuo = dividendo % divisor
print(f"{dividendo} entre {divisor} da un cociente {cociente} y un residuo {residuo}")

#EJERCICIO 4
edad = 70
if edad > 17 and edad < 60:
  print("Puede pasar")
elif edad > 59:
  print("Puede pasar y tiene descuento ")
else:
  print(" No puede pasar")