# -*- coding: utf-8 -*-
"""Tabla de Mutiplicar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibFuYgLL6Gu30PySf6P-wAQCtgBpAyq1
"""

numero = int(input("ingresa un numero"))
for i in range(1,11):
  resultado = numero * i
  print(f"{numero} x {i} es igual a {resultado}")

